// Generated by Scripts/version.py from Version.json.
// Refresh with `python3 Scripts/version.py generate`.

/// CLI metadata shared by the executable and library documentation.
package enum ComputerMCPCLI {
  /// Current package CLI version.
  package static let version = "1.2.2"

  /// Current package build number.
  package static let build = "38"

  /// Version string exposed by the command-line executable.
  package static let releaseVersion = "\(version) (\(build))"
}
