import ComputerMCPPlatform

package typealias WorkspacePathResolver = ComputerMCPPlatform.WorkspacePathResolver
package typealias WorkspacePathResolutionError = ComputerMCPPlatform.WorkspacePathResolutionError
