#!/usr/bin/env python3
"""Update authoritative product metadata or check it without modifying files."""
import argparse
import json
from pathlib import Path
import plistlib
import re
import subprocess
import sys

ROOT = Path(__file__).resolve().parent.parent
DECLARATION = "Version.json"
PLIST = "Resources/ComputerMCPApp/Info.plist"
SWIFT = "Sources/ComputerMCP/ComputerMCPCLI.swift"
SEMVER = re.compile(r"(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\Z")


def require(condition, message):
    if not condition:
        raise ValueError(message)


def version_tuple(version):
    require(isinstance(version, str) and SEMVER.fullmatch(version), "Expected MAJOR.MINOR.PATCH without leading zeroes")
    return tuple(map(int, version.split(".")))


def declaration(data):
    require(set(data) == {"schema_version", "version", "build"} and data["schema_version"] == 1, "Unsupported version declaration")
    version_tuple(data["version"])
    require(type(data["build"]) is int and 0 < data["build"] <= 2_147_483_647, "Build must be a positive 32-bit integer")
    return data


def read(root):
    return declaration(json.loads((root / DECLARATION).read_text()))


def run(args, cwd, timeout=30):
    result = subprocess.run(args, cwd=cwd, capture_output=True, text=True, timeout=timeout)
    require(result.returncode == 0, f"Command failed ({args[0]}): {result.stderr.strip()}")
    return result.stdout.strip()


def swift(data):
    return f'''// Generated by Scripts/version.py from Version.json.
// Refresh with `python3 Scripts/version.py generate`.

/// CLI metadata shared by the executable and library documentation.
package enum ComputerMCPCLI {{
  /// Current package CLI version.
  package static let version = "{data['version']}"

  /// Current package build number.
  package static let build = "{data['build']}"

  /// Version string exposed by the command-line executable.
  package static let releaseVersion = "\\(version) (\\(build))"
}}
'''


def generated_plist(root, data):
    text = (root / PLIST).read_text()
    for key, value in (("CFBundleShortVersionString", data["version"]), ("CFBundleVersion", str(data["build"]))):
        pattern = r"(<key>" + key + r"</key>\s*<string>)[^<]*(</string>)"
        text, count = re.subn(pattern, lambda m: m[1] + value + m[2], text)
        require(count == 1, f"Expected one {key} field in {PLIST}")
    return text


def generate(root, data):
    # Validate every output before writing either file.
    plist = generated_plist(root, data)
    (root / PLIST).write_text(plist)
    (root / SWIFT).write_text(swift(data))


def check_progress(data, previous):
    require(version_tuple(data["version"]) >= version_tuple(previous["version"]), "Product version moved backwards")
    require(data["build"] >= previous["build"], "Build number moved backwards")
    if data["version"] != previous["version"]:
        require(data["build"] > previous["build"], "A new product version requires a higher build number")


def check_bump(data, version, build, kind):
    proposed = declaration({"schema_version": 1, "version": version, "build": build})
    check_progress(proposed, data)
    major, minor, patch = version_tuple(data["version"])
    expected = {
        "fix": (major, minor, patch + 1),
        "feature": (major, minor + 1, 0),
        "breaking": (major + 1, 0, 0),
        "candidate": (major, minor, patch),
    }[kind]
    require(version_tuple(version) == expected, f"{kind} requires version {'.'.join(map(str, expected))}")
    require(build > data["build"], "A candidate revision requires a higher build number")
    return proposed


def check_dependencies(root):
    pins = json.loads((root / "Package.resolved").read_text())["pins"]
    identities = [pin["identity"] for pin in pins]
    require(len(set(identities)) == len(identities), "Duplicate dependency lock identity")
    package = json.loads(run(["/usr/bin/swift", "package", "dump-package"], root, timeout=120))
    indexed = {pin["identity"]: pin for pin in pins}
    for dep in package["dependencies"]:
        require(set(dep) == {"sourceControl"}, "Release dependencies must use public source-control versions")
        source = dep["sourceControl"][0]
        pin = indexed.get(source["identity"])
        require(pin is not None, f"Missing dependency lock: {source['identity']}")
        url = source["location"]["remote"][0]["urlString"]
        require(pin["location"] == url, f"Dependency location mismatch: {source['identity']}")
        requirement = source["requirement"]
        resolved = pin["state"].get("version")
        require(resolved is not None, f"Dependency must lock a release: {source['identity']}")
        if "exact" in requirement:
            require(requirement["exact"] == [resolved], f"Exact dependency version mismatch: {source['identity']}")
        elif "range" in requirement:
            limits = requirement["range"][0]
            require(version_tuple(limits["lowerBound"]) <= version_tuple(resolved) < version_tuple(limits["upperBound"]), f"Dependency outside compatible range: {source['identity']}")
        else:
            raise ValueError(f"Non-release dependency requirement: {source['identity']}")
    receipts = []
    for pin in pins:
        state = pin["state"]
        version_tuple(state.get("version"))
        require(re.fullmatch(r"[0-9a-f]{40}", state.get("revision", "")), f"Invalid locked commit: {pin['identity']}")
        require(pin["location"].startswith("https://") and "@" not in pin["location"], "Dependency URL must be public HTTPS")
        # SwiftPM normalizes a two-component tag such as 0.4 to version 0.4.0.
        versions = [state["version"]]
        if state["version"].endswith(".0"):
            versions.append(state["version"].rsplit(".", 1)[0])
        refs = [f"refs/tags/{prefix}{version}{peel}" for version in versions for prefix in ("", "v") for peel in ("", "^{}")]
        try:
            output = run(["git", "ls-remote", "--exit-code", pin["location"], *refs], root)
        except ValueError as error:
            raise ValueError(f"Cannot verify public dependency tag {pin['identity']} {state['version']}: {error}") from error
        matches = dict(line.split()[::-1] for line in output.splitlines())
        revisions = {matches.get(ref + "^{}", matches[ref]) for ref in matches if not ref.endswith("^{}")}
        require(revisions == {state["revision"]}, f"Public tag and locked commit differ: {pin['identity']}")
        receipts.append({"identity": pin["identity"], **state})
    return receipts


def check(root, args):
    data = read(root)
    require((root / SWIFT).read_text() == swift(data), f"Generated CLI metadata drifted; run {Path(__file__).name} generate")
    require((root / PLIST).read_text() == generated_plist(root, data), "App metadata differs from Version.json")
    if args.base:
        # Before the declaration existed, the committed App metadata owns the historical baseline.
        files = run(["git", "ls-tree", "--name-only", args.base, "--", DECLARATION], root)
        if files:
            previous = declaration(json.loads(run(["git", "show", f"{args.base}:{DECLARATION}"], root)))
        else:
            old = plistlib.loads(run(["git", "show", f"{args.base}:{PLIST}"], root).encode())
            previous = {"version": old["CFBundleShortVersionString"], "build": int(old["CFBundleVersion"])}
        check_progress(data, previous)
    if args.tag:
        require(args.tag == "v" + data["version"], "Tag version differs from the declaration")
        require(run(["git", "rev-parse", args.tag + "^{}"], root) == run(["git", "rev-parse", "HEAD"], root), "Tag commit differs from candidate source")
    expected = f"{data['version']} ({data['build']})"
    if args.cli:
        require(run([str(args.cli.resolve()), "--version"], root) == expected, "CLI runtime version differs from declaration")
    if args.app:
        info = plistlib.loads((args.app / "Contents/Info.plist").read_bytes())
        require(info["CFBundleShortVersionString"] == data["version"] and info["CFBundleVersion"] == str(data["build"]), "Packaged App version differs from declaration")
        require(run([str((args.app / "Contents/Resources/computer-mcp").resolve()), "--version"], root) == expected, "Embedded CLI version differs from declaration")
    result = {"status": "passed", **data}
    if args.dependencies:
        result["dependencies"] = check_dependencies(root)
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    sub = parser.add_subparsers(dest="operation", required=True)
    show = sub.add_parser("show")
    show.add_argument("--field", choices=("version", "build"))
    sub.add_parser("generate")
    update = sub.add_parser("update")
    update.add_argument("--version", required=True)
    update.add_argument("--build", required=True, type=int)
    update.add_argument("--kind", required=True, choices=("fix", "feature", "breaking", "candidate"))
    update.add_argument("--reason", required=True)
    verify = sub.add_parser("check")
    verify.add_argument("--base")
    verify.add_argument("--tag")
    verify.add_argument("--cli", type=Path)
    verify.add_argument("--app", type=Path)
    verify.add_argument("--dependencies", action="store_true")
    args = parser.parse_args()
    root = args.root.resolve()
    data = read(root)
    if args.operation == "show":
        print(data[args.field] if args.field else json.dumps(data))
    elif args.operation == "check":
        print(json.dumps(check(root, args), sort_keys=True))
    elif args.operation == "generate":
        generate(root, data)
    else:
        require(args.reason.strip(), "An upgrade rationale is required")
        proposed = check_bump(data, args.version, args.build, args.kind)
        require(not run(["git", "tag", "--list", "v" + args.version], root), "A formal version is immutable; select the next version")
        generated_plist(root, proposed)
        (root / DECLARATION).write_text(json.dumps(proposed, indent=2) + "\n")
        generate(root, proposed)
        print(json.dumps({"component": "computer-mcp", "previous": data, "current": proposed, "kind": args.kind, "reason": args.reason}, ensure_ascii=False))


if __name__ == "__main__":
    try:
        main()
    except (ValueError, OSError, KeyError, subprocess.SubprocessError) as error:
        print(f"Version check failed: {error}", file=sys.stderr)
        sys.exit(1)
